"use client";

import { motion } from "framer-motion";

export default function AiPrototypeDisclaimer() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="mx-auto w-full max-w-4xl rounded-[2.2rem] border border-[#B3945E]/35 bg-gradient-to-br from-[#FFFDF9]/95 via-[#FAF6EF]/90 to-[#F5ECE0]/85 p-6 sm:p-8 shadow-[0_12px_40px_rgba(179,148,94,0.07)] backdrop-blur-2xl space-y-4 text-left"
    >
      {/* Header Badge */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-600/30 bg-amber-500/10 px-3 py-1 text-[0.68rem] font-bold uppercase tracking-[0.2em] text-amber-900">
            <span className="h-1.5 w-1.5 rounded-full bg-amber-600 animate-pulse" />
            AI Prototype Advisory
          </span>
          <span className="text-xs text-black/45 font-mono">AI Prototype · Research Demo</span>
        </div>

        <span className="text-[0.7rem] font-medium text-black/50 uppercase tracking-[0.16em]">
          Educational & Research Demo
        </span>
      </div>

      {/* Title */}
      <h4 className="font-serif text-lg sm:text-2xl font-medium text-[#1A1A1A]">
        Experimental AI Notice & Human Discretion Advisory
      </h4>

      {/* Advisory Body */}
      <div className="space-y-2.5 text-xs sm:text-sm text-black/75 leading-relaxed font-normal">
        <p>
          <strong className="font-semibold text-black">Nirāma (निराम)</strong> is a concept prototype and research demonstration for AI-powered food label transparency.
        </p>

        <p>
          All nutritional verdicts, 4pt micro-text ingredient extractions, disguised sugar analyses, and additive health flags are <strong className="font-semibold text-black">generated by multimodal Artificial Intelligence</strong>. While our pipeline references FSSAI regulatory benchmarks and public toxicology databases, <span className="font-medium text-amber-950 underline decoration-amber-400 decoration-1 underline-offset-2">AI models are probabilistic and can make mistakes</span>, misread distorted packaging ink, or hallucinate ambiguous ingredient lists.
        </p>

        <p className="text-black/65 text-xs">
          This digital tool is provided strictly for educational awareness and label literacy. It does not constitute certified medical, pediatric, or clinical dietary advice. Consumers should always inspect the physical product packaging and consult licensed healthcare professionals for dietary decisions.
        </p>
      </div>

      {/* Key Takeaways / Micro-Pills */}
      <div className="pt-2 flex flex-wrap items-center gap-2 text-[0.7rem] text-black/60 font-medium border-t border-[#B3945E]/20">
        <span className="inline-flex items-center gap-1 rounded-full bg-black/[0.03] border border-black/5 px-3 py-1">
          ✦ 100% AI Synthesized
        </span>
        <span className="inline-flex items-center gap-1 rounded-full bg-black/[0.03] border border-black/5 px-3 py-1">
          ⚡ Prototype Stage
        </span>
        <span className="inline-flex items-center gap-1 rounded-full bg-black/[0.03] border border-black/5 px-3 py-1">
          🔬 Research Grade
        </span>
        <span className="inline-flex items-center gap-1 rounded-full bg-black/[0.03] border border-black/5 px-3 py-1">
          🔎 Verify Physical Labels
        </span>
      </div>
    </motion.div>
  );
}
